### ISSUE TITLE
Ruby 2.5 doesn't include bundler

### ISSUE THREAD

**Issue by pyama86** [cloudfoundry/bundler-cnb#2]
Hi Team!
I happend into the following error.

```
Implement detect
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

I think the reason is that ruby 2.5 doesn't include bundler.
I'm currently using `cloudfoundry/cnb:latest` image, should I use any other image?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dfreilich** [comment]
Hi @pyama86 , thanks for opening the issue! It's odd that you saw that, given that the `ruby-cnb` and `bundler-cnb` haven't been added to the builder yet. Were you adding them manually (eg. `pack build ... --builder cloudfoundry/cnb:latest --buildpack...`)?

We haven't yet implemented any functionality in the `bundler-cnb`, and so it fails out pretty fast (hence the error above). We don't have immediate plans to work on it, but if you want to add functionality and add a PR, we'd be happy to pull it in.

**Comment by pyama86** [comment]
Hi @dfreilich, thanks for your response.

> if you want to add functionality and add a PR, we'd be happy to pull it in.

I got it.
I'm going to create PR.
thanks!
